$("#mypanorama").ipanorama({
  "theme": "ipnrm-theme-default",
  "autoLoad": false,
  "autoRotate": false,
  "autoRotateSpeed": 0.001,
  "autoRotateInactivityDelay": 3000,
  "mouseWheelPreventDefault": true,
  "mouseWheelRotate": false,
  "mouseWheelRotateCoef": 0.2,
  "mouseWheelZoom": false,
  "mouseWheelZoomCoef": 0.05,
  "hoverGrab": false,
  "hoverGrabYawCoef": 20,
  "hoverGrabPitchCoef": 20,
  "grab": true,
  "grabCoef": 0.1,
  "pinchZoom": true,
  "pinchZoomCoef": 0.1,
  "showControlsOnHover": false,
  "showSceneThumbsCtrl": false,
  "showSceneMenuCtrl": false,
  "showSceneNextPrevCtrl": true,
  "showShareCtrl": false,
  "showZoomCtrl": true,
  "showFullscreenCtrl": true,
  "showAutoRotateCtrl": false,
  "sceneThumbsVertical": true,
  "sceneThumbsStatic": false,
  "title": true,
  "compass": false,
  "keyboardNav": false,
  "keyboardZoom": false,
  "sceneNextPrevLoop": false,
  "popover": true,
  "popoverPlacement": "top",
  "hotSpotBelowPopover": true,
  "popoverShowTrigger": "hover",
  "popoverHideTrigger": "leave",
  "mobile": false,
  "sceneId": "scene1",
  "sceneFadeDuration": 3000,
  "sceneBackgroundLoad": false,
  "scenes": {
    "scene1": {
      "type": "sphere",
      "cubeTextureCount": "single",
      "sphereWidthSegments": 100,
      "sphereHeightSegments": 40,
      "image": "https://gif.cmtt.space/3/club/fc/a6/1a/9bb035ac2369cd.jpg",
      "saveCamera": true,
      "title": "main",
      "titleHtml": false,
      "titleSelector": null,
      "hotSpots": [
        {
          "title": null,
          "yaw": 293.11435,
          "pitch": -18.45691,
          "sceneId": "scene2",
          "imageUrl": "",
          "imageWidth": null,
          "imageHeight": null,
          "link": null,
          "linkNewWindow": false,
          "popoverHtml": true,
          "popoverContent": null,
          "popoverSelector": null,
          "popoverLazyload": true,
          "popoverShow": false
        }
      ]
    },
    "scene2": {
      "type": "sphere",
      "cubeTextureCount": "single",
      "sphereWidthSegments": 100,
      "sphereHeightSegments": 40,
      "image": "https://gif.cmtt.space/3/club/fc/a6/1a/9bb035ac2369cd.jpg",
      "saveCamera": true,
      "title": "sec",
      "titleHtml": false,
      "titleSelector": null
    }
  }
});